### PR TITLE
Enable auto-resizing to container div

### LINKED ISSUE #316: Should enable auto resizing to container div

### LINKED ISSUE #374: Dynamic resizing of ggvis plots in shiny apps
Hi, The problem was described here. (the problem of resizing a ggvis plot when Shiny app will be opened in diferent size of monitor).
http://stackoverflow.com/questions/27693277/dynamic-resizing-of-ggvis-plots-in-shiny-apps

### PR DESCRIPTION
**Pull request by wch**
Closes #316. Closes #374.

Example app (container div is shaded yellow):

```R
library(shiny)
library(ggvis)

shinyApp(
  ui = fluidPage(
    div(style = "width:300px; height:300px; background: #ffd;",
      ggvisOutput("plot")
    )
  ),
  server = function(input, output) {
    mtcars %>% ggvis(~wt, ~mpg) %>% layer_points() %>%
      set_options(width = "auto", height = "auto", resizable=FALSE) %>%
      bind_shiny("plot")
  }
)
```

This app demonstrates how the height and width settings interact work when the wrapper div has a specified size:

```R
library(shiny)
library(ggvis)

shinyApp(
  ui = fluidPage(sidebarLayout(
    sidebarPanel(
      radioButtons("width", "Width", c("auto", "400")),
      radioButtons("height", "Height", c("auto", "400")),
      radioButtons("resizable", "Resizable (enabled only if width and height are fixed)",
                   c("Yes", "No"))
    ),
    mainPanel(
      div(style = "width:300px; height:300px; background: #ffd;",
        ggvisOutput("plot")
      )
    )
  )),
  server = function(input, output) {
    reactive({
      resizable <- (input$resizable == "Yes")

      mtcars %>% ggvis(~wt, ~mpg) %>% layer_points() %>%
      set_options(width = input$width, height = input$height, resizable=resizable)
    }) %>%
      bind_shiny("plot")
  }
)
```

### CODE REVIEW

**Comment by Nicolabo** [comment]
I updated `Shiny` package but honestly I do not see any changes.

**Comment by wch** [comment]
@Nicolabo This example resizes the plot to the width of the window. (Auto-height with HTML/CSS can be tricky.)

```R
library(shiny)
library(ggvis)

shinyApp(
  ui = fluidPage(
    div(style = "height: 300px; background: #ffd;",
      ggvisOutput("plot")
    )
  ),
  server = function(input, output) {
    mtcars %>% ggvis(~wt, ~mpg) %>% layer_points() %>%
      set_options(width = "auto", height = "auto", resizable=FALSE) %>%
      bind_shiny("plot")
  }
)
```

**Comment by Nicolabo** [comment]
I do not know if it works correctly for me. I can see only a yellow rectangle without plot. Rectangle works fine and resizes  anytime but the plot does not show up.

**Comment by wch** [comment]
That's strange. The plot should fit inside the yellow rectangle. Can you post the output of `devtools::session_info()`, and also report what browser you're using?

**Comment by Nicolabo** [comment]
Session info----------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.1 (2014-07-10)
 system   x86_64, darwin13.4.0       
 ui       RStudio (0.98.1103)         
 language (EN)                        
 collate  pl_PL.UTF-8                 
 tz       Europe/Rome                 

Packages--------------------------------------------------------------------------------------------------------------------
 package    * version     date       source                           
 assertthat   0.1         2013-12-06 CRAN (R 3.1.1)                   
 DBI          0.3.1       2014-09-24 CRAN (R 3.1.1)                   
 devtools     1.6         2014-09-23 CRAN (R 3.1.1)                   
 digest       0.6.4       2013-12-03 CRAN (R 3.1.1)                   
 dplyr        0.4.1.9000  2015-03-12 Github (hadley/dplyr@2e298fc)    
 ggvis      * 0.4.0.9000  2015-03-08 Github (rstudio/ggvis@1cfbe13)   
 htmltools    0.2.6       2014-09-08 CRAN (R 3.1.1)                   
 httpuv       1.3.2       2015-03-12 Github (rstudio/httpuv@0a6413c)  
 httr         0.5         2014-09-02 CRAN (R 3.1.1)                   
 jsonlite     0.9.12      2014-09-27 CRAN (R 3.1.1)                   
 lazyeval     0.1.10.9000 2015-03-08 Github (hadley/lazyeval@08f5900) 
 magrittr     1.5         2014-12-02 Github (smbache/magrittr@5d1e526)
 mime         0.2         2014-09-26 CRAN (R 3.1.1)                   
 R6           2.0         2014-08-19 CRAN (R 3.1.1)                   
 Rcpp         0.11.3      2014-09-29 CRAN (R 3.1.1)                   
 RCurl        1.95.4.3    2014-07-29 CRAN (R 3.1.1)                   
 rstudioapi   0.1         2014-03-27 CRAN (R 3.1.1)                   
 shiny      * 0.11.1.9003 2015-04-02 Github (RStudio/Shiny@babc59f)   
 stringr      0.6.2       2012-12-06 CRAN (R 3.1.1)                   
 xtable       1.7.4       2014-09-12 CRAN (R 3.1.1) 

I use Chrome.

**Comment by wch** [comment]
You need to update your version of ggvis.

**Comment by Nicolabo** [comment]
I thought about it. Nice job! Really appreciate it.

**Comment by bertoli12** [comment]
Hi there,

I am having trouble with the auto sizing. I have made sure to update all of my packages.

The size of the graph is correct when I change the width to "auto", but the graph is blank until I resize the chart. Once I resize it, the data shows up.

Any thoughts?

**Comment by wch** [comment]
@bertoli12 You can file a new issue for this. Please supply a small reproducible example, and the output of `devtools::session_info()`.

**Pull request merged**
